2019-09-16 06:54:31,976 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 06:58:27,011 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/case_test_common.py changed, reloading.
2019-09-16 07:01:38,014 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/case_test_common.py changed, reloading.
2019-09-16 07:03:34,860 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 07:15:04,951 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 07:15:30,335 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 07:25:14,514 [ERROR] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py", line 24, in index
    case_test_common.ope_cfg = OperationCFG(deal_file_path.get("config"))
TypeError: __init__() missing 1 required positional argument: 'section'
2019-09-16 07:29:15,152 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 08:05:01,419 [ERROR] [/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py] [read_data ][/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py:25]- 操作JSON类读取数据异常，异常原因：Extra data: line 4 column 2 (char 244)
2019-09-16 08:05:01,419 [ERROR] [/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py] [read_data ][/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py:25]- 操作JSON类读取数据异常，异常原因：Extra data: line 4 column 2 (char 244)
2019-09-16 08:05:01,419 [ERROR] [/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py] [get_data_for_key ][/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py:39]- 操作JSON类根据key获取value异常，异常原因：'NoneType' object is not subscriptable
2019-09-16 08:05:01,420 [ERROR] [/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py] [read_data ][/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py:25]- 操作JSON类读取数据异常，异常原因：Extra data: line 4 column 2 (char 244)
2019-09-16 08:05:01,420 [ERROR] [/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py] [get_data_for_key ][/home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/python_excel/utils/operation_json.py:39]- 操作JSON类根据key获取value异常，异常原因：'NoneType' object is not subscriptable
2019-09-16 08:15:05,620 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 08:44:15,940 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /favicon.ico
2019-09-16 08:45:00,282 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/case_test_common.py changed, reloading.
2019-09-16 08:56:37,655 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/case_test_common.py changed, reloading.
2019-09-16 09:01:13,194 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/project_tree/test2/report20190916/manage20190916085920.html
2019-09-16 09:03:12,604 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/project_tree/test2/report20190916/manage20190916085920.html
2019-09-16 09:06:35,732 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/project_tree/test2/report20190916/manage20190916090615.html
2019-09-16 09:09:00,826 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/case_test_common.py changed, reloading.
2019-09-16 09:32:34,760 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /
2019-09-16 09:36:12,516 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/project_tree/test2/report/20190916/manage20190916093540.html
2019-09-16 09:37:01,104 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 09:38:08,411 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/upload_case/views.py changed, reloading.
2019-09-16 09:46:17,936 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /home/ma/PycharmProjects/Auto_InterFace_GUI/InterfaceTest/project_tree/test2/report/20190916/manage20190916093940.html
2019-09-16 09:49:11,270 [WARNING] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/log.py] [log_response ][django.request:228]- Not Found: /index/static/case/BQ_JC_QZ_CASE.xlsx
2019-09-16 09:51:18,471 [INFO] [/home/ma/PycharmProjects/Auto_InterFace_GUI/venv/lib/python3.6/site-packages/django/utils/autoreload.py] [trigger_reload ][django.utils.autoreload:217]- /home/ma/PycharmProjects/Auto_InterFace_GUI/Auto_InterFace_GUI/urls.py changed, reloading.
